VPC_CIDR_BLOCK   = "10.0.0.0/16"
SUB_CIDR_BLOCK   = "10.0.1.0/24"
PROJECT_NAME     = "Jenkins"
AZ               = "us-east-1a"
PORTS_EC2        = [22, 8080]
PUBLIC_KEY_PATH  = "~/.ssh/id_rsa.pub"
PRIVATE_KEY_PATH = "~/.ssh/id_rsa"
EC2_USER         = "ubuntu"
PORTS_ELB        = [80, 443]
DOMAIN_NAME      = "israeltrello.be"
